apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-gate-master-v000
  namespace: spinnaker
  labels:
    app: redis
    stack: gate
    detail: master
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: redis-gate-master-v000
  template:
    metadata:
      labels:
        replication-controller: redis-gate-master-v000
        load-balancer-redis-gate-master: "true"
        app: redis
        stack: gate
        detail: master
    spec:
      containers:
      - name: redis-master
        image: gcr.io/kubernetes-spinnaker/redis:v0.0.3
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
