apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: DECK_HOST
          value: 0.0.0.0
        - name: DECK_PORT
          value: "9000"
        envFrom:
        - configMapRef:
            name: deck-env
        image: ghcr.io/spinnaker/deck:main-latest
        name: deck
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 9000
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: config
          # https://github.com/spinnaker/deck/blob/deba01ed7ba275194f51bcc0cbf414bbf3266562/docker/run-apache2.sh#L78
          mountPath: "/opt/spinnaker/config/"
          readOnly: true
      # TODO:
      # securityContext:
      #   runAsUser: 10111
      #   runAsGroup: 10111
      #   runAsNonRoot: true
      #   fsGroup: 10111
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: deck
