server:
  port: 8090

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

kayenta:
  atlas:
    enabled: false
#    stageTimeoutMinutes: 3
#    maxBackoffPeriodSeconds: 30
#    accounts:
#      - name:
#        endpoint:
#          baseUrl: http://localhost:7101
#        namespace:
#        supportedTypes:
#          - METRICS_STORE

  google:
    enabled: false
#    accounts:
#      - name:
#        project:
#        jsonPath:
#        bucket:
#        rootFolder: kayenta
#        supportedTypes:
#          - METRICS_STORE
#          - OBJECT_STORE
#          - CONFIGURATION_STORE

  azure:
    enabled: false
#    accounts:
#      - name:
#        storageAccountName:
#        accountAccessKey:
#        container:
#        rootFolder: kayenta
#        endpointSuffix: core.windows.net
#        supportedTypes:
#          - OBJECT_STORE
#          - CONFIGURATION_STORE

  aws:
    enabled: false
#    accounts:
#      - name:
#        bucket:
#        rootFolder: kayenta
#        You can set credentials that you supply explicitly (see: AwsManagedAccount.ExplicitAwsCredentials)
#        explicitCredentials:
#          accessKey: explicitAccessKey
#          secretKey: explicitSecretKey
#          sessionToken: explicitSessionToken (optional)
#        supportedTypes:
#          - OBJECT_STORE
#          - CONFIGURATION_STORE

  datadog:
    enabled: false
#    metadataCachingIntervalMS: 900000
#    accounts:
#      - name: my-datadog-account
#        apiKey: xxxx
#        applicationKey: xxxx
#        supportedTypes:
#          - METRICS_STORE
#        endpoint.baseUrl: https://app.datadoghq.com

  graphite:
    enabled: false
#    accounts:
#      - name: my-graphite-account
#        endpoint:
#          baseUrl: http://localhost
#        supportedTypes:
#          - METRICS_STORE

  newrelic:
    enabled: false
#    accounts:
#    - name: my-newrelic-account
#      apiKey: xxxx
#      applicationKey: xxxx
#      defaultScopeKey: server_scope # Optional, if omitted every request must supply the _scope_key param in extended scope params
#      defaultLocationKey: server_region # Optional, if omitted requests must supply the _location_key if it is needed.
#      supportedTypes:
#        - METRICS_STORE
#      endpoint.baseUrl: https://insights-api.newrelic.com

  prometheus:
    enabled: false
#   metadataCachingIntervalMS: 60000
#    accounts:
#      - name: my-prometheus-account
#        endpoint:
#          baseUrl: http://localhost:9090
#        username: xxxx # Optional, for use when protecting prometheus with basic auth
#        password: xxxx # Optional, for use when protecting prometheus with basic auth
#        usernamePasswordFile: xxxx # Optional, for use when protecting prometheus with basic auth
#        bearerToken: xxxx # Optional, for use when protecting prometheus with bearer token
#        supportedTypes:
#          - METRICS_STORE

  signalfx:
    enabled: true
#    accounts:
#      - name: sfx-integration-test-account
#        accessToken: ${kayenta.signalfx.apiKey} # The sfx api token
#        endpoint.baseUrl: https://stream.signalfx.com # Optional defaults to https://stream.signalfx.com
#        defaultScopeKey: server_scope # Optional, if omitted every request must supply the _scope_key param in extended scope params
#        defaultLocationKey: server_region # Optional, if omitted requests must supply the _location_key if it is needed.
#        supportedTypes:
#          - METRICS_STORE

  wavefront:
   enabled: false
#   accounts:
#      - name:
#        endpoint:
#          baseUrl:
#        apiToken:
#        supportedTypes:
#          - METRICS_STORE

  gcs:
    enabled: false

  blobs:
    enabled: false

  s3:
    enabled: false

  stackdriver:
    enabled: false
#    metadataCachingIntervalMS: 60000

  memory:
    enabled: false

  configbin:
    enabled: false

  remoteJudge:
    enabled: false
#    endpoint:
#      baseUrl: http://remotejudge.example.com/path/to/service

# Enable the SCAPE endpoint that has the same user experience that the Canary StageExecution in Deck/Orca has.
  standaloneCanaryAnalysis:
    enabled: false

# Retry configuration for metrics fetching from metrics storage (see: MetricsRetryConfigurationProperties)
  metrics:
    retry:
      series: SERVER_ERROR
      statuses: REQUEST_TIMEOUT, TOO_MANY_REQUESTS
      attempts: 10
      backoffPeriodMultiplierMs: 1000

  # Set the serialization options for springboot.jackson
  serialization:
    writeDatesAsTimestamps: false
    writeDurationsAsTimestamps: false

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
# To fix issue with kayenta-integration-tests while upgrading spring-boot to 2.3.12
# https://github.com/micrometer-metrics/micrometer-docs/issues/123
management.metrics.export.graphite.graphite-tags-enabled: false

keiko:
  queue:
    redis:
      queueName: kayenta.keiko.queue
      deadLetterQueueName: kayenta.keiko.queue.deadLetters

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: true

swagger:
  enabled: true
  title: Kayenta API
  description:
  contact:
  patterns:
    - /admin.*
    - /canary.*
    - /canaryConfig.*
    - /canaryJudgeResult.*
    - /credentials.*
    - /fetch.*
    - /health
    - /judges.*
    - /metadata.*
    - /metricSetList.*
    - /metricSetPairList.*
    - /metricServices.*
    - /pipeline.*
    - /standalone.*

spring:
  liquibase:
    change-log: classpath:db/changelog-master.yml
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
