language: java
jdk:
- openjdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle
notifications:
  slack:
    secure: JtMdRjbeLkUjKe/IjiB7UEvEcOcKHT6lAVT31Hn5Kkw/U28JuscxOYTSD79b66Kxnq8kDFiWyhyUP5PfLp4+maX1zrYdieX0WhUkknsEvfP3Evcfcp6wYNexmxuTn3cmFLcSxKOQSr0KJ93YmBCHaGk/d2zt9NxhpXabtKptMfPrHFf9YvQMAtTLjU6U4pDvBOJGcW6KSD7ZwPYJXvyDCabm3EhCLG09IpJNj9P1XtpEBRA8FSWqLbAmmSx2yLsWfGvuf94niJ7C4xnAt2IRUTtYPwLv0H/ezptKLOhN1QOlkl784f7KHMimETyEFAnE94sjCJUQt32oB/nvowUjWtVajUKYYR0BmjtcD1jwS+nOwy+5sfBb8DN0JkEVijWoxXdlxY1jUZrGy0oF51UFxHvZYMxr20ScDqM+4SOq+TvRHpygRT3nRlcP8HugJErF1La8+sboDuTGy8Z6CI7or55/xrrXAhXolimc7s2TKNTpSqA9tGLehTBFcc/HDyG2MdvNxzCXNb4NHGKtLFvULI5I3nsr0eWpbmeWOGIeqG5dX9zr/YvyMfAXQf8qScQBQlwdS671lV2roJYZooZf5WI1wE/Bb3qApPXqSlW6EkyCUxRgJ4lCAgpbpU0B/ChyoKbFokRviinQFoVPQpkLiPGZMmrqRUnxh/NKN2OZymw=
env:
  global:
  - secure: rItFfaK85MWIa0Dp9nsOwK5670d2JFA0bqfTCSuJNKfaFi4+45nQFUcVOccR2zY7oKCyylXxiDZKCz2P1j4gY+cYcxc0gC5VZzrGaP3Zde9EFdd3x9L4rxFxmjW09LNxFn1ilH8+KUE56W5Ak8o+9x9oYdEqP/B9N5omSf31mJtOveYCm6I8YHyEDI9/UznwzZMYNMTWYZyaOQZl8TVZVJS+oWBLgw4QlsllWc4J9RoPizFe51kCFgB2E8Ze0e05Kr76oZJ+64kBov36sUaOcSOls6eJ6VPN8lVRG9EQi75NnGlbmZvg8MT19v6uByuk14QvRbvr/B5lRC6GleH+kQ9ZrSFnLhYUMsq3tDrhdnsUtPZOYe93Tt/CsDhxuGpFsRYG8Itc8bDnyMbdhi0Eg5tTY/hlTG+e3/aUmIN5Ea/eqPmzGOcAzbLsC+zVx7FcC0C88EBQ/L/UDmH2htVs3L0MvBTquzm3suJ433eT8XoDV0YyfQ3mzf2PitJOVf+QNJxpLC1NwLmgca73HRgbsZ1pqkX/P6roOSZWdrMy+jwLupqxGwOuDR2yc7YILVEkFm2qfY67xs+r+ZMqVM2iB3mqwRIxLop8M0OvWnxS7VhfUD3ti5LGlGebMXLQXPJIsDNTHCTwephTFutvAlkr175VOyODAk32PsT5NWUkZXk=
  - secure: WGxAwuZM9idIQLUm69HfHZ1p+tQjTYVCXFNbIojrgcdO62z9UCIzpc+bPqYNI9KsxkWqtRK61JFRVh+OTN3Ua5g36dVIRG9Qs1N4RqkkIXpXlL6XU89J1BnLCHUEp3/JeD76I0rFVJSpVKea1clB45+VahgW8FkWKeNhJNHgDpQfifdVU0db/Hr4/423n5KHeOyek8MevO9EiQts8Fd4XQrYIcAfF+FIdQROzfEMEMDh8tvKCDzDkYqgtm2XjIPnBK2PzMbas5l8wzknMFmPaRnp3LC/etFyGsY2qdaEp5YrLVPtQMd4pZLA7x3xUXn7k1wRMAswvo2AuRny2CMSgf7xhU1Rf2HG5qUr2r38os9a2729WBslVkoeMW5tKDfQko425fUdhkeSpQbqVa1DPgMohdg9Of+c4jvQLE2rjSFev1RbKDAWRtw+/KSF3Ghz9O18k9glZYtNjmBNZzrrRGwXnoI+jldZAyEN7smpfeqdR3wa3jIwea3O7C+xmsI75vDI7R+0XGJkGs+2RjS/xISgXqD+MoiZnXVqsDlUCXNDEnWIGZMMg41FjYzmkWK2YzgZepuk4x5qQpUBZNe8QmHee5/pBHigtmC474nie4ciijtAQNiLoBKBlHnLUlbgPo1zODUKGa0K5ewoE8gASHZStVzAWtG4YFbqNVNdAEk=
git:
  depth: 250
