language: java
jdk:
- openjdk8
dist: trusty
sudo: true
install: true
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: VA8UxPAiEWYEEbG6B4QQ+77gXPCHCGSWU4NBGtwrnuKy8BLqKPLlumSeQbFI7+mamGOvTjqSCa04Gloz/rpbSIEe0NVTsBZoFQRvRx1xWpiPmBxXVJcyuEgnEtIoUq3p+4wSSapfCf/sZ5ixU7HXXbIxr7MlsYfnzXu4Wt2Pb9eotEqp9BJlskq5sYL93LpF8GfB8M/3Mu5URgTdhy4V+zdw4+fBF2my1wSIXhBwmX+lO95qMyWWzOOTUDZhg6Y48KC9iao9zkd86EKFYECnhZ2iUiuMQf1d8Lphd3qOY3w6aCRRpJBKkm35o7RaHsTwLXWSqAOKzvaOMmUYS/OWJ4SnXTJxEmwVqlCYEgf02JzC0RCV49Jn/JMK/By2XM0N1DalGvwujlvxb0c+HuUEYU5gZVV25rIjZFy2pSOxiwtsehWHDMuRlz+4SIX7rdJIy9gi49nIY3aF23TLW/2cBPzw6vchdNSlcetWTBAwYl3Xs2RX+DofL4eoQqdqYTPQ37YNeM1WUb1/1pKqJZyawc7aoqbi9JPgY0/YKMLsJ+SiDxEGkFhXbSkaI8XoVDoJtdXB1LLMpNj+VvHjhtYxs8o3eKDIWxNiFdMlqZ7Cu5anVIJbu2Wy88hq2AAiQN+B88gaPBz5LN0xpxBibSCYHD23mvU3IskIMrzLzb+chSg=
  - secure: RxP+LUmGsidEOPTLHLo24L15v0OvreyvbNfcM1d6SqrAr/hyrf7OKMMN4v27xRUtlyUmKOUz/M1463caSS46qs5QaFqlO4boi1kwykKtqCEkAaoqhdX82QU4m73nzcSyug14X/r9EOdBlfeffNnZ+YpiDQ/ntZJHtLQHFKjnqj/Z+K+HXfa7LoB2cp0VTq8SgQrmU0a2rtWiA2sHEh39lw5JS6eSTxJ7xqhb/0TXuyqQ7pRrPIJ7pUkdcvawarCVMbt7ezGFel8oqMeiKjNHbztVFXgh8C9lu2ggvmpohg10zFqjzOdfJy7Vc/1VIOxgA5k2i7EpDmXonOENfkhNj0P/0Yv8H7Pb4xaGFXxvRk2bpypA7SNb9aCLRoYvZ2NDqLKs/N9NBkjcEfVRdVxAAlcxn8m6bBaLGAxDS7wjqtRTiNpHHb85lyibuIsmerVm0EiO3H8vIQAlMOS5yY7HAxe71i1b7XAjmmqRZRhjNrAOHqhObrIR7vtwNBU/xv2SKpRg30A3LYNt9d6dp/ndFIi/mo2tmLB+ZRMVd9BzlaXbf98GZJPtxHfH01u/mGsp6gwbFeUqyERh3QSFzoUKzNU13fQONNexj+syii1rqZTpHreQ30JtDHpKZVHzR1cPPZAYkF9Ue2YMjtlNZt/p6n0mN+cX5zOvMUbAFtc77IA=
