language: java
jdk:
- oraclejdk8
sudo: false
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle
env:
  global:
  - secure: VvtyCNa8F0SpzJqBBE9VmtpoMh0IqEpnTQJLVxosxvBCIjCcYA50k1pLQnQt3+J8Cdm6+ezEgU+0Vp15dk+e9bInjn1Vjvn1DzaSqxhuSjMtK0ZAdCwt1pzXwYTwTrSzLMetkrlQMLzvlRtpmNWuvl8n+Vt5e6o0G6fN4LFIDY4suPYC/bwSKPXFSEgmbiZ2+GWtT4g/XAKkpYnd9KLHqSfD3yud7ireBoXl5h49HKxX/FtzfbtXF4K6nf1gpEVobHpeUnkt074Re9FYxzekoYUPzFrZrHTqlbcpTRwTgsDL2AvL8UznzWQoxm1Mo8aIRnMpB/Ev0N6CqRCtSwWNqRXaXYDmyEnunwFbJwijcnzJ7ydKEwrrxKSaDa4OOU4TVWsJvBn61wwwk4C57xejn0R4VB1eQhiRhZ2ma9PQ3h31mqCRBrIN3f2cpyp3ah+6S/uHcb2PLmGMOf4lBkWrhe8zuOvDkDC7+3vb+o38SSPwpkPkA5MpISzJKaYVX4kLXV7WirBq69Y8+ijVRyWDrxCT3bKcfcUI7LB3ovWeMi0qOQ3bmu2YKJLhyKy88XIbJ9E0aqqFu0cU+VQS+VhatbGj7XG+1zWDkgrScRfP7j8JGy53mKVLrcdA/I+HqIcZRaqFXdTiZNhjmseqEdUZ3sFvJdPyZOswZq4JH690Ydg=
  - secure: KoEtIyDAo+cTCNZGYb86/Q18H3rOvXzCd/vfFCDn5KLpbJRCaLq3Qnil4yvyeHrgFFsH2NqVxkSDpeVMtAE/ZtYE1bM8Jl0BxiJZi+lHYoiX4j6wJ6JR8p2cAwwnxyy44JAuxGXzHJwp4s9Q9sTJCaz8+Ejn+QfujtJQ8OL/MCt8Z+T3cPEa50asF28e/0MhFEdM1au/tH/fnuQhKPJ+KSDq4NKStXKgzorfdxAuMLGDIY8a03ZwtkQ5KqkzbRfiIYQYrq9vM2UagR2Nj+Rn19P6VMeoXoa84gZBUIdLEqeol0mLtJyMCKNDtaTmyeMX2WFFNY7LNOzmmOf5wYQY764Y1eKgELBGd8NX5x/2djoRXRDyKEMqIgHJLmdPy5o1Qh9GELCR6y1CYWNM7zOlObz08a6Q57xyh2qyWbnGqz3lsJkR2q8AMUCQ6zq5vPnlFjpDMEsRrpMUf1lRiluUv1g9nWQRW0Y98JRqiyQWFpYBdkX5Sbz6bBzbnQ5+wGkXX6IM8hmXouhJqoT+oRBsGXS1wEpemnYzx+CU6jSi5vZ0qxNeTc7gmdXXvHViVAONOgtlJu2/9Lkjb0bKPE+KFuwYWl80uH4mtKQD0k2T+yhVcZIm7PnP7mikpf78SQ2q5FZFYNRkAzisnFtZsU47j6q8bIHnvUFmNBMt+7EKw/E=
