language: java
jdk:
- openjdk8
sudo: required
dist: trusty
services:
- docker
before_install:
  - docker pull andrewgaul/s3proxy
  - docker run -d -p9999:80 --env S3PROXY_AUTHORIZATION="none" --env JCLOUDS_PROVIDER="filesystem" --env JCLOUDS_IDENTITY="remote-identity" --env JCLOUDS_CREDENTIAL="remote-credential" andrewgaul/s3proxy
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle
notifications:
  slack:
    secure: d7br5L1JRshwLRd5aBfl8J5lkux5WdObUaNk5/E11b9kSNG5HYchhQMCwOyMgmEDfUG9NQntK14RHhS9LTg35e/HuZfy+QzT7WPFszL73b/poMF1pErTqebfmya0QjzZDBzHDFmB/Zk9ei2mgXoDDdqLuU1HOzeeLD//5qcA741clt9mQgD/4Qbv0A6tJmkQg5L+gdVvayE5YGFEJCzUMJlbIuAQTLDcIpeHIkkEJooI5YmsEVLp2xqrPdjRNUnVp3pgbtwC28IteOuWCoDKAhkd3ud3nS7YCfrrnh9MmZoK1pxU4XAtiaPyKjJ+OeGGa6cDiW9T3Aj4NOL1hckLZ8QYracI9VVF8Thzf2FKrYyTSjXsGR3UocvQoeLq5hjcdn6hGG9bWZUPsyHjx62KryV6GDigVNz1Te/+BWqPnUHOrFezWvYwLuV+qSJIqMIH9aUvzZTVbj7QP1cX+GE5DK0hRFGCtEVYOZbVjduvSrXV/9pCA+9OExUj8h9XhuckxCI207t1PoDjlg4WzZTe9gyzoPf+KRi43U3oUJn81iiCfCGLaaDAO+jdiQaz4bDt1IdhUff8bsdgETY/f7vd1+orpyDuhbUzBhVptWK1H3Zj35DzTrEry8iH6aoW3bQHy11pmfEbZEVb4hHdhl2OrhhXC0f3l72av1Hwo48i484=
env:
  global:
  - secure: xkyEZfe2ArnXvPan+HKHY75SN6rWu3fWQvWaNsP0/rKfi1/53rKIuUz7bfwpgx/o5RIPOKiMpmTWw9UC/aAboK/9Kmx2Eh3gyxjvDfA3GaEHIq+vZh6YrALVoAMqiHgs222ORjAXF5vYhNtQLVn2EnpgtQTjuSLa+g5Z27r5PCqmKVF+HBfgzDHVXiZ/taYdLmpX4f1e8Oi1OGO4Nn4Q87CwpmVKP5BqDc6+5XYa7MPzQbtcCzvMetdxzYPtcy/dJLg3Izo7bokDiNKsWOTa/f0qCVNpevey40SMnsNgbmJ4WYxZ03wFAnbfX5WaVtJd+Bt6myRffEfnUZ+ektl+heoQtB7n82pV//jqz84r5qZ3p7NtlTneMQLY3gSyG3/nn+wAX8UI+jgZ0J+CoZdZRqnVSq+Sj2Z5nt46WFicZ9mS8g9AAPUa4sQaj1tJJzBq6UGWH7FekGaZF1qXvu/6qEslwlGMUHSI70h7asMtJ7BNpkVw8LDM46aaUwyR0zEv3MwNHwHF8RKuBPytzuOBAN/NOwCacvtlPZlyZRyvFBs5twcl68GM7v0TrkzRMRSi0IxOIBLw2qyl+OqR42y8eZHVy+5XBrlRf4/PAiQ13IvOrmfuY35Ek9MzKEUvx/I+3ety87dY+Zrq8HrSTurdW+sK/jpB9G28ZNfvH9aY1+k=
  - secure: lOCkYfc2lBBNfyb9NVYgNpqgMGedQ/ZdzPJ7Og2R0pjKXcmGTf172x+5UGt1QfMuCt0F7H6yCJXtz0uwodRsY1nEzX/a/elobjBdaDsshlNpWq1uRqYrBCIAzwRHH6Y1yl5G6vrveqVvY/nMfBhdEUFH8mXSuV7b7qyN9WdPAM4VU2WwfP6lSGrNzabbOkbyna4XFMudpItCGvPbfj+E+4PZfZaM69ZEteHiKhadtlWuEg4B0W+Ga2DRCEaxFniSKKzGvuRO+aNG9xb6oie8BkDHRN3ytf00fetxpMN6j5QSdlNBKW8sXIBc7chpTOZEA0dOSLpKM6H2hlSdhvwQbY7X1p3Ft6dGmkVVSgDCOOKzSbxEXmt6kSbjrtSPD6N/pHut6X/GS2dw1iUUj7ZFjAZPJmNSL8dWb3Sam0PH+OQtgHEItf5fu81JBPGcttWaah1Kd5ij4pAOB5njonm7EBScf5AOAp1W69Gk+nIcL3DD0q5RgZFh18Bac386GJcHci2tVegWXsDIsXURKG61Q3dmzAbHd0EFTON3Lw9M+JTXjpxrXm/YXv5pIgZDECKqJbgiG5U4hAAJrBXqHuCveyi3opi3JzhhQbUOCl5vGdiqly4CzZv+pqNXD+nw719JgmIPVpwaM7nvzZV1+Lmh6esXLo0/k0X7Zv5vH2v4uIE=
