# Validate will override builtin defaults with
# $HOME/.spinnaker/validate_bom.yml if found.
#
# The --default_args_file <path> can be used to specify an additional
# override file (of higher precedence)
#
# Config parameters passed as command line flags are of the highest precedence.


# log_dir: ./validate_bom_results
# monitoring_enabled: false
# monitoring_system: file
# metric_name_scope: buildtool
# influxdb_url: http://localhost:8086
# influxdb_database: SpinnakerValidate
# influxdb_reiterate_gauge_secs: 60
# includdb_add_context_labels:


###############################################
#  Deployment Module Configuration Parameters
###############################################

#############
# Kubernetes
#############
# deploy_k8s_namespace: spinnaker


#############
# Aws
#############
# deploy_aws_name:
# deploy_aws_pem_path:
# deploy_aws_security_group:
# deploy_aws_ami: ami-0b542c1d
# deploy_aws_region: us-east-1


#############
# Azure
#############
# deploy_azure_location: eastus
# deploy_azure_resource_group:
# deploy_azure_azure_name:


#############
# Google
#############
# deploy_hal_google_service_account:
# deploy_google_machine_type: n1-standard-4
# deploy_google_image_family: ubuntu-1404-lts
# deploy_google_image_project: ubuntu-os-cloud
# deploy_google_project:
# deploy_google_zone: us-central1-f
# deploy_google_instance:
# deploy_google_network: default
# deploy_google_use_internal_ip: true
# deploy_google_tags: spinnaker-validation-instance
#
# NOTE: Tags are just for user convienence. There are no implications
#       to having any or their values in the validation process itself.


#########################
# Halyard and Deployment 
#########################
# halyard_install_script: https://raw.githubusercontent.com/spinnaker/halyard/master/install/nightly/InstallHalyard.sh
# halyard_version:          # only set to override
# halyard_bucket_base_url:  # only set to override
# halyard_config_bucket:    # only set to override
# halyard_config_bucket_credentials:  # only set if needed by halyard_config_bucket
# spinnaker_repository: https://dl.bintray.com/spinnaker-releases/debians
# spinnaker_registry: gcr.io/spinnaker-marketplace
# deploy_spinnaker_type: # localdebian or distributed
# deploy_hal_platform:   # one of gce, ec2, azure
# deploy_haly_user:      # LOGNAME environment variable
# deploy_version: master-latest-unvalidated
# deploy_deploy: true
# deploy_undeploy: true
# deploy_always_collect_logs: false


###########################################
#  Config Module Configuration Parameters
###########################################

################
# Azs Storage
################

# storage_azs_account_name:
# storage_azs_credentials:

################
# S3 Storage
################
# storage_s3_bucket:
# storage_s3_assume_role: role/spinnakerManaged
# storage_s3_region:
# storage_s3_endpoint:
# storage_s3_access_key_id:
# storage_s3_credentials:


################
# Gcs Storage
################
# storage_gcs_bucket:
# storage_gcs_location: us-central1
# storage_gcs_project:
# storage_gcs_credentials:

#######################
# GcsArtifact Storage
#######################

# artifact_gcs_credentials:
# artifact_gcs_account_name:


################
# AWS
################
# aws_access_key_id:
# aws_credentials:
# aws_account_name: my-aws-account
# aws_account_id:
# aws_account_role: role/spinnakerManaged
# aws_account_regions: us-east-1,us-west-2
# aws_account_pem_path:


################
# Appengine
################
# appengine_account_project:
# appengine_account_name: my-appengine-account
# appengine_account_credentials:
# appengine_account_git_username:
# appengine_account_git_https_credentials:
# appengine_account_git_oauth_credentials:
# appengine_ssh_private_key_path:
# appengine_private_key_passphrase:
# appengine_local_repository_directory:


################
# Azure
################
# azure_account_credentials:
# azure_account_name: my-azure-account
# azure_account_client_id:
# azure_account_subscription_id:
# azure_account_tenant_id:
# azure_account_object_id:
# azure_account_default_key_value:
# azure_account_default_resource_group:
# azure_account_package_resource_group:
# azure_account_package_storage_account:


################
# DC/OS
################
# dcos_cluster_name: my-dcos-cluster
# dcos_cluster_url:
# dcos_account_name: my-dcos-account
# dcos_account_docker_account:
# dcos_account_uid:
# dcos_account_credentials:


################
# Google
################
# google_account_project:
# google_account_credentials:
# google_account_name: my-google-account


################
# Kubernetes
################
# k8s_account_credentials:
# k8s_account_name: my-kubernetes-account
# k8s_account_context:
# k8s_account_namespaces: validate-bom
# k8s_account_docker_account:


################
# Docker
################
# docker_account_address:
# docker_account_name: my-docker-account
# docker_account_registry_username:
# docker_account_credentials
# docker_account_repositories


#############
# Canary
#############
# canary_aws: false
# canary_google: false
# canary_prometheus_account: my-prometheus-account
# canary_prometheus_url:
# canary_stackdriver: false


################
# Jenkins
################
# jenkins_master_name:
# jenkins_master_address:
# jenkins_master_user:
# jenkins_master_credentials:  # or value in JENKINS_MASTER_PASSWORD


##########################
# Logging and Monitoring
##########################
# google_cloud_logging: false
# monitoring_prometheus_gateway:
# monitoring_install_which:  # one of : prometheus, datadog, stackdriver

#############################################
#  Testing Module Configuration Parameters
#############################################

# testing_enabled: true
# test_profiles: all_tests.yaml
# test_service_startup_timeout: 300
# test_extra_profile_bindings:
# test_concurrency:
# test_default_quota: google_backend_service=5,google_forwarding_rules=10,google_ssl_certificates=5,google_cpu=20,appengine_deployment=1
# test_quota:
# test_include: .*
# test_exclude:
# test_stack:

