netflix:
  appinfo:
    name: 'igor'

spinnaker:
  build:
    pollInterval: 30
  pollingSafeguard:
    # A lower value can help prevent accidental re-triggers of pipelines, but may require hands-on operations if
    # set low.
    # See code documentation for more details. Class [PollingSafeguardProperties] in
    # https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/IgorConfigurationProperties.groovy#L47
    itemUpperThreshold: 1000

endpoints.health.sensitive: false

spring.jackson.serialization.write_dates_as_timestamps: false

server.port: 8088

#artifact:
#  This is a feature toggle for decoration of artifacts.
#  decorator:
#    enabled: true
#    fileDecorators:
#       - type: mavenUrl
#         decoratorRegex: /[\/\:.]*\/([a-zA-Z-]+)\-([\d\.]+\-[\d\.]+)[a-z\-\d]+\.[jw]ar$/
#         identifierRegex: /https?\:\/\/[\/\:.]*\/([a-zA-Z-]+)\-([\d\.]+\-[\d\.]+)[a-z\-\d]+\.[jw]ar$/

#travis:
#  enabled: true
#
#  Repository sync makes a call to travis telling travis to sync repos against github.
#  This makes new repos with builds in travis the github user has access to tracked by spinnaker.
#  repositorySyncEnabled: true
#
#  This grace period gives travis some time to make the logs available. If a build just finished when we try to fetch
#  logs, parts of the logs might not be present. Increase this timeout if artifacts are randomly missing.
#  newBuildGracePeriodSeconds: 10
#
#  Travis names are prefixed with travis- inside igor.
#  masters:
#    - name: ci # This will show as travis-ci inside spinnaker.
#      baseUrl: https://travis-ci.org
#      address: https://api.travis-ci.org
#      githubToken: XXXXXX
#      numberOfRepositories: 25 # How many repositories the travis integration should fetch from the api each time the
#                               # poller runs. Should be set a bit higher than the expected maximum number of
#                               # repositories built within the poll interval.
#
#  Additional regexes to use when parsing build logs in search for uploaded
#  artifacts, besides the default regexes which match on the output of the
#  `art` CLI.  The provided example would match on the output from Gradle's
#  maven-publish plugin.
#  regexes:
#  - Upload https?:\/\/.+\/(.+\.(deb|rpm))$
