apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
spec:
  replicas: 0  # FIXME: Crash loops due to configuration issue
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: ghcr.io/spinnaker/keel:main-latest
        name: keel
        ports:
        - name: http
          containerPort: 7010
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: config
          mountPath: "/opt/spinnaker/config/"
          readOnly: true
      serviceAccountName: keel
      securityContext:
        runAsUser: 10111
        runAsGroup: 10111
        runAsNonRoot: true
        fsGroup: 10111
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: spinnaker
          - configMap:
              name: keel
