apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
components:
- components/mariadb
- components/redis
- overlays/config
namespace: spinnaker
images:
- name: ghcr.io/spinnaker/clouddriver
  newTag: main-latest
- name: ghcr.io/spinnaker/deck
  newTag: main-latest
- name: ghcr.io/spinnaker/echo
  newTag: main-latest
- name: ghcr.io/spinnaker/fiat
  newTag: main-latest
- name: ghcr.io/spinnaker/front50
  newTag: main-latest
- name: ghcr.io/spinnaker/gate
  newTag: main-latest
- name: ghcr.io/spinnaker/igor
  newTag: main-latest
- name: ghcr.io/spinnaker/kayenta
  newTag: main-latest
- name: ghcr.io/spinnaker/keel
  newTag: main-latest
- name: ghcr.io/spinnaker/orca
  newTag: main-latest
- name: ghcr.io/spinnaker/rosco
  newTag: main-latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: spinnaker
