server:
  port: 8090

kayenta:
  atlas:
    enabled: false
#    endpoint:
#      baseUrl: http://localhost:7101
#    accounts:
#      - name:
#        namespace:
#        supportedTypes:
#          - METRICS_STORE

  google:
    enabled: false
#    accounts:
#      - name:
#        project:
#        jsonPath:
#        bucket:
#        rootFolder:
#        supportedTypes:
#          - METRICS_STORE
#          - OBJECT_STORE

  gcs:
    enabled: false

  stackdriver:
    enabled: false

  redis:
    enabled: false

  memory:
    enabled: false

management.security.enabled: false

queue.redis.enabled: true
executionLog.redis.enabled: false

swagger:
  enabled: true
  title: Kayenta API
  description:
  contact:
  patterns:
    - /canary.*
    - /canaryConfig.*
    - /credentials.*
    - /fetch.*
    - /judges.*
    - /metricSetList.*
    - /metricSetPairList.*
    - /pipeline.*
    - /healthcheck.*
