apiVersion: apps/v1
kind: Deployment
metadata:
  name: orca
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: ghcr.io/spinnaker/orca:main-latest
        name: orca
        ports:
        - name: http
          containerPort: 8083
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: config
          mountPath: "/opt/spinnaker/config/"
          readOnly: true
      serviceAccountName: orca
      securityContext:
        runAsUser: 10111
        runAsGroup: 10111
        runAsNonRoot: true
        fsGroup: 10111
      terminationGracePeriodSeconds: 720
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: spinnaker
          - configMap:
              name: orca
