server:
  port: 8087

rush:
  baseUrl: http://localhost:8085
  # TODO(duftler): Figure out the right way to set this dynamically.
  configDir: /some/path/to/config/packer

executionStatusToBakeStates:
  associations:
    - executionStatus: PREPARING
      bakeState: PENDING
    - executionStatus: FETCHING_IMAGE
      bakeState: PENDING
    - executionStatus: RUNNING
      bakeState: RUNNING
    - executionStatus: CANCELED
      bakeState: CANCELED
    - executionStatus: SUCCESSFUL
      bakeState: COMPLETED
    - executionStatus: FAILED
      bakeState: CANCELED

executionStatusToBakeResults:
  associations:
    - executionStatus: SUCCESSFUL
      bakeResult: SUCCESS
    - executionStatus: FAILED
      bakeResult: FAILURE

# If a repository is set here, it will be added by packer as an apt repository when baking images for GCE and AWS.
# It is safe to leave this out (or blank) if you do not need to configure your own apt repository.
# The following commented-out line is an example of what a valid entry looks like.
# debianRepository: http://dl.bintray.com/spinnaker/ospackages ./

defaultCloudProviderType: aws

aws:
  enabled: ${AWS_ENABLED:false}
  bakeryDefaults:
    awsAssociatePublicIpAddress: true
    templateFile: aws-ebs.json
    defaultVirtualizationType: hvm
    operatingSystemVirtualizationSettings:
    # TODO(duftler): Identify proper base amis.
    # TODO(duftler): Support additional store types beyond ebs.
    # TODO(duftler): Support additional operating systems.
    # TODO(duftler): Feels like just about everything here could be (optionally) specified per bake.
    - os: ubuntu
      virtualizationSettings:
      - region: us-east-1
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-d4aed0bc
        sshUserName: ubuntu
      - region: us-west-2
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-59396769
        sshUserName: ubuntu
      - region: us-east-1
        virtualizationType: pv
        instanceType: m3.medium
        sourceAmi: ami-8007b2e8
        sshUserName: ubuntu
#      No exact equivalent available in us-west-2
#      - region: us-west-2
#        virtualizationType: pv
#        instanceType: m3.medium
#        sourceAmi: 
#        sshUserName: ubuntu
    - os: trusty
      virtualizationSettings:
      - region: us-east-1
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-9eaa1cf6
        sshUserName: ubuntu
      - region: us-west-2
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-3d50120d
        sshUserName: ubuntu
      - region: us-east-1
        virtualizationType: pv
        instanceType: m3.medium
        sourceAmi: ami-98aa1cf0
        sshUserName: ubuntu
      - region: us-west-2
        virtualizationType: pv
        instanceType: m3.medium
        sourceAmi: ami-37501207
        sshUserName: ubuntu

docker:
  enabled: ${DOCKER_ENABLED:false}
  bakeryDefaults:
    targetRepository: ${DOCKER_TARGET_REPOSITORY:}
    templateFile: docker.json
    operatingSystemVirtualizationSettings:
    - os: ubuntu
      virtualizationSettings:
        sourceImage: ubuntu:precise
    - os: trusty
      virtualizationSettings:
        sourceImage: ubuntu:trusty

google:
  enabled: ${GOOGLE_ENABLED:false}
  gce:
    bakeryDefaults:
      zone: us-central1-f
      useInternalIp: false
      templateFile: gce.json
      operatingSystemVirtualizationSettings:
      - os: ubuntu
        virtualizationSettings:
          sourceImage: ubuntu-1204-precise-v20150910
      - os: trusty
        virtualizationSettings:
          sourceImage: ubuntu-1404-trusty-v20150909a

swagger:
  enabled: true
  title: Spinnaker Rosco API
  description:
  contact:
  patterns:
    - .*api/v1.*
