# This file is intended to override the default configuration in the spinnaker.yml file.
# In order for Spinnaker to discover it, it must be copied to a file named
# "spinnaker-local.yml" and placed in the $HOME/.spinnaker directory.

providers:
  aws:
    # If you want to deploy some services to Amazon Web Services (AWS),
    # set enabled and provide primary credentials for deploying.
    # Enabling AWS is independent of other providers.
    enabled: ${SPINNAKER_AWS_ENABLED}
    defaultRegion: ${SPINNAKER_AWS_DEFAULT_REGION}
    defaultIAMRole: BaseIAMRole
    primaryCredentials:
      name: my-aws-account
      # You can use a standard $HOME/.aws/credentials file instead of providing
      # these here. If provided here, then start_spinnaker will set environment
      # variables before starting up the subsystems that interact with AWS.
      access_key_id:
      secret_key:

  google:
    # If you want to deploy some services to Google Cloud Platform (google),
    # set enabled and provide primary credentials for deploying.
    # Enabling google is independent of other providers.
    enabled: ${SPINNAKER_GOOGLE_ENABLED}
    defaultRegion: ${SPINNAKER_GOOGLE_DEFAULT_REGION}
    defaultZone: ${SPINNAKER_GOOGLE_DEFAULT_REGION}-b
    primaryCredentials:
      name: my-google-account
      # The project is the Google Project ID for the project to manage with Spinnaker.
      # The jsonPath is a path to the JSON service credentials downloaded from the
      # Google Developer's Console.
      project: ${SPINNAKER_GOOGLE_PROJECT_ID}
      jsonPath:

services:
  default:
    # These defaults can be modified to change all the spinnaker subsystems
    # (clouddriver, gate, etc) at once, but not external systems (jenkins, etc).
    # Individual systems can still be overriden using their own section entry
    # directly under 'services'.
    protocol: http    # Assume all spinnaker subsystems are using http
    host: localhost   # Assume all spinnaker subsystems are on localhost
    primaryAccountName: ${providers.google.primaryCredentials.name}

  redis:
    # If you are using a remote redis server, you can set the host here.
    # If the remote server is on a different port or url, you can add
    # a "port" or "baseUrl" field here instead.
    host: localhost

  cassandra:
    # If you are using a remote cassandra server, you can set the host here.
    # If the remote server is on a different port or url, you can add
    # a "port" or "baseUrl" field here instead. You may also need to set
    # the cluster name. See the main spinnaker.yml file for more attributes.
    host: localhost

  docker:
    # This target repository is used by the bakery to publish baked docker images.
    # Do not include http://.
    targetRepository: # Optional, but expected in spinnaker-local.yml if specified.

  jenkins:
    # If you are integrating Jenkins, set its location here using the baseUrl
    # field and provide the username/password credentials.
    # You must also enable the "igor" service listed seperately.
    #
    # If you have multiple jenkins servers, you will need to list
    # them in an igor-local.yml. See jenkins.masters in config/igor.yml.
    #
    # Note that jenkins is not installed with Spinnaker so you must obtain this
    # on your own if you are interested.
    defaultMaster:
      name: Jenkins # The display name for this server
      baseUrl:
      username:
      password:

  igor:
    # If you are integrating Jenkins then you must also enable Spinnaker's
    # "igor" subsystem.
    enabled: false

  rush:
    # Spinnaker's "rush" subsystem is used by the "rosco" bakery.
    # You need to provide the fully-qualified path to the directory containing the packer templates.
    # They typically live in rosco's config/packer directory.
    configDir:

  echo:
    # allow pipeline triggers to run periodically via cron expressions  
    cron:
      enabled: true
    # If you wish for spinnaker to send notifications, configure the following blocks
    notifications:
      mail:
        enabled: false
        host: # the smtp host
        fromAddress: #the address for which emails are sent from
      hipchat:
        enabled: false
        url: # the hipchat server to connect to
        token: #the hipchat auth token
      sms:
        enabled: false
        account: # twilio account id
        token: # twilio auth token
        from: # phone number by which sms messages are sent


