# This file is intended to override the default configuration in the spinnaker.yml file.
# In order for Spinnaker to discover it, it must be copied to a file named
# "spinnaker-local.yml" and placed in the $HOME/.spinnaker directory.

providers:
  aws:
    # If you want to deploy some services to Amazon Web Services (AWS),
    # set enabled and provide primary credentials for deploying.
    # Enabling AWS is independent of other providers.
    enabled: false
    defaultRegion: us-east-1
    defaultIAMRole: BaseIAMRole
    primaryCredentials:
      name: my-aws-account
      # You can use a standard $HOME/.aws/credentials file instead of providing
      # these here. If provided here, then start_spinnaker will set environment
      # variables before starting up the subsystems that interact with AWS.
      access_key_id:
      secret_key:

  google:
    # If you want to deploy some services to Google Cloud Platform (google),
    # set enabled and provide primary credentials for deploying.
    # Enabling google is independent of other providers.
    enabled: false
    defaultRegion: us-central1
    defaultZone: us-central1-f
    primaryCredentials:
      name: my-google-account
      # The project is the Google Project ID for the project to manage with Spinnaker.
      # The jsonPath is a path to the JSON service credentials downloaded from the
      # Google Developer's Console.
      project:
      jsonPath:

  cf:
    # If you want to deploy some services to Cloud Foundry (cf),
    # set enabled and provide primary credentials for deploying.
    # Enabling cf is independent of other providers.
    enabled: false
    defaultOrg: spinnaker-cf-org
    defaultSpace: spinnaker-cf-space
    primaryCredentials:
      name: my-cf-account
      api: my-cf-api-uri
      console: my-cf-console-base-url
    # You must also supply cf.account.username and cf.account.password through env properties

services:
  default:
    # These defaults can be modified to change all the spinnaker subsystems
    # (clouddriver, gate, etc) at once, but not external systems (jenkins, etc).
    # Individual systems can still be overriden using their own section entry
    # directly under 'services'.
    protocol: http    # Assume all spinnaker subsystems are using http
    host: localhost   # Assume all spinnaker subsystems are on localhost
    primaryAccountName: ${providers.google.primaryCredentials.name}

  redis:
    # If you are using a remote redis server, you can set the host here.
    # If the remote server is on a different port or url, you can add
    # a "port" or "baseUrl" field here instead.
    host: localhost

  cassandra:
    # If you are using a remote cassandra server, you can set the host here.
    # If the remote server is on a different port or url, you can add
    # a "port" or "baseUrl" field here instead. You may also need to set
    # the cluster name. See the main spinnaker.yml file for more attributes.
    host: localhost

  docker:
    # Spinnaker's "rush" subsystem uses docker to run internal jobs.
    # Note that docker is not installed with Spinnaker so you must obtain this
    # on your own if you are interested.
    enabled: false
    baseUrl: # Expected in spinnaker-local.yml
    # This target repository is used by the bakery to publish baked docker images.
    # Do not include http://.
    targetRepository: # Optional, but expected in spinnaker-local.yml if specified.

    # You'll need to provide it a Spinnaker account to use.
    # Here we are assuming the default primary acccount.
    #
    # If you have multiple accounts using docker then you will need to
    # provide a rush-local.yml.
    # For more info see docker.accounts in config/rush.yml.
    primaryAccount:
      name: ${services.default.primaryAccountName}
      url:  ${services.docker.baseUrl}
      registry: ${services.dockerRegistry.baseUrl}

  dockerRegistry:
    baseUrl:

  jenkins:
    # If you are integrating Jenkins, set its location here using the baseUrl
    # field and provide the username/password credentials.
    # You must also enable the "igor" service listed seperately.
    #
    # If you have multiple jenkins servers, you will need to list
    # them in an igor-local.yml. See jenkins.masters in config/igor.yml.
    #
    # Note that jenkins is not installed with Spinnaker so you must obtain this
    # on your own if you are interested.
    defaultMaster:
      name: Jenkins # The display name for this server
      baseUrl:
      username:
      password:

  igor:
    # If you are integrating Jenkins then you must also enable Spinnaker's
    # "igor" subsystem.
    enabled: false

  rush:
    # Spinnaker's "rush" subsystem is used by the "rosco" bakery.
    # You'll need to provide it a Spinnaker account to use.
    # Here we are assuming the default primary acccount.
    primaryAccount: ${services.default.primaryAccountName}
