# NOTE: Copy this file to ~/.spin/config

gate:
  endpoint: https://my-spinnaker-gate:8084
auth:
  enabled: true
  x509:
    # See https://www.spinnaker.io/setup/security/authentication/ssl/ and
    # https://www.spinnaker.io/setup/security/authentication/x509/ for guides on creating
    # the key and cert files.
    certPath: "~/.spin/certpath"
    keyPath: "~/.spin/keypath" # This should point to an _unencrypted_ keyfile.

    # Pipe to start a multi-line string. This is necessary to import the b64 cert/key value.
    cert: |
      -----BEGIN CERTIFICATE-----
      BLAHBLAHBLAHBLAHBLAHBLAH==
      -----END RSA PRIVATE KEY-----
    # Pipe to start a multi-line string. This is necessary to import the b64 cert/key value.
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      BLAHBLAHBLAHBLAHBLAHBLAH==
      -----END RSA PRIVATE KEY-----

  oauth2:
    # The following is an example for Google's OAuth2 endpoints.
    # The values for these are specific to your OAuth2 provider.
    authUrl: https://accounts.google.com/o/oauth2/auth
    tokenUrl: https://accounts.google.com/o/oauth2/token

    # See https://www.spinnaker.io/setup/security/authentication/oauth/providers/
    # to see examples for acquiring clientId/clientSecret.
    clientId:
    clientSecret:
    scopes:
    - scope1
    - scope2

  iap:
    # check detailed config in https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_desktop_app
    oauthClientId: "xxxx-xxxx.apps.googleusercontent.com"
    oauthClientSecret: "oauth client secret"
    iapClientId: "yyyy-yyyy.apps.googleusercontent.com"
