server:
  port: ${services.rosco.port:8087}
  address: ${services.rosco.host:localhost}

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

aws:
  enabled: ${providers.aws.enabled:false}

azure:
  enabled: ${providers.azure.enabled:false}
  accounts:
    - name: ${providers.azure.primaryCredentials.name}
      clientId: ${providers.azure.primaryCredentials.clientId}
      appKey: ${providers.azure.primaryCredentials.appKey}
      tenantId: ${providers.azure.primaryCredentials.tenantId}
      subscriptionId: ${providers.azure.primaryCredentials.subscriptionId}
      packerResourceGroup: ${providers.azure.primaryCredentials.packerResourceGroup}
      packerStorageAccount: ${providers.azure.primaryCredentials.packerStorageAccount}

docker:
  enabled: ${services.docker.enabled:false}
  bakeryDefaults:
    targetRepository: ${services.docker.targetRepository}

google:
  enabled: ${providers.google.enabled:false}
  accounts:
    - name: ${providers.google.primaryCredentials.name}
      project: ${providers.google.primaryCredentials.project}
      jsonPath: ${providers.google.primaryCredentials.jsonPath}
  gce:
    bakeryDefaults:
      zone: ${providers.google.defaultZone}

rosco:
  configDir: ${services.rosco.configDir}

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: ${services.spectator.webEndpoint.enabled:false}
    prototypeFilter:
      path: ${services.spectator.webEndpoint.prototypeFilter.path:}

  stackdriver:
    enabled: ${services.stackdriver.enabled}
    projectName: ${services.stackdriver.projectName}
    credentialsPath: ${services.stackdriver.credentialsPath}
