server:
  port: 8087

clouddriver:
  baseUrl: http://localhost:8081
front50:
  baseUrl: http://localhost:8080
orca:
  baseUrl: http://localhost:8083
echo:
  baseUrl: http://localhost:8086

queue:
  poll:
    frequency:
      ms: 1000

keiko:
  queue:
    redis:
      queueName: keel.queue
      deadLetterQueueName: keel.queue.deadLetters

redis:
  connection: redis://localhost:6379
#  connectionPrevious: null
