server:
  port: 8084

services:
  oort:
    baseUrl: http://localhost:8081
  orca:
    baseUrl: http://pond-${netflix.stack}.${netflix.environment}.netflix.net
  front50:
    baseUrl: http://front50-${netflix.stack}.${netflix.environment}.netflix.net
  mort:
    baseUrl: http://localhost:8082
  kato:
    baseUrl: http://localhost:8501
#optional services:
  echo:
    enabled: false
  mayo:
    enabled: false
  flapjack:
    enabled: false
  igor:
    enabled: false

redis:
  connection: redis://localhost:6379