server:
  port: 7002

services:
  front50:
    baseUrl: http://localhost:8080

redis:
  connection: redis://$REDIS_HOST:6379

aws:
  enabled: ${AWS_ENABLED:false}

google:
  enabled: ${GOOGLE_ENABLED:false}

  kmsServer: http://localhost:7909
  accounts:
    - name: $GOOGLE_ACCOUNT_NAME  # A spinnaker account used for GCE
      project: $GOOGLE_MANAGED_PROJECT_ID
