discoveryHosts:
  - http://us-east-1.discoveryprod.netflix.net:7001
  - http://us-west-1.discoveryprod.netflix.net:7001
  - http://us-west-2.discoveryprod.netflix.net:7001
  - http://eu-west-1.discoveryprod.netflix.net:7001

security:
  basic:
    enabled: false

oort.baseUrl: http://oort.prod.netflix.net
kato.baseUrl: http://kato.prod.netflix.net
echo.baseUrl: http://echo.prod.netflix.net
mort.baseUrl: http://mort.prod.netflix.net
mayo.baseUrl: http://mayo.prod.netflix.net
front50.baseUrl: http://front50.prod.netflix.net
flapjack.baseUrl: http://flapjack.prod.netflix.net

services:
  - name: oort
    group: applications
    baseUrl: ${oort.baseUrl}
  - name: pond
    group: orchestration
    baseUrl: ${pond.baseUrl}
  - name: echo
    group: events
    baseUrl: ${echo.baseUrl}
  - name: flapjack
    group: tags
    baseUrl: ${flapjack.baseUrl}
  - name: front50
    group: metadata
    baseUrl: ${front50.baseUrl}
  - name: mort
    group: credentials
    baseUrl: ${mort.baseUrl}
  - name: kato
    group: credentials
    baseUrl: ${kato.baseUrl}
  - name: mayo
    group: config
    baseUrl: ${mayo.baseUrl}