discoveryHosts:
  - http://us-east-1.discoveryprod.netflix.net:7001
  - http://us-west-1.discoveryprod.netflix.net:7001
  - http://us-west-2.discoveryprod.netflix.net:7001
  - http://eu-west-1.discoveryprod.netflix.net:7001

services:
  - name: oort
    group: applications
    baseUrl: http://oort.prod.netflix.net
  - name: pond
    group: orchestration
    baseUrl: http://pond.prod.netflix.net
  - name: echo
    group: events
    baseUrl: http://echo.prod.netflix.net
  - name: flapjack
    group: tags
    baseUrl: http://flapjack.prod.netflix.net
  - name: front50
    group: metadata
    baseUrl: http://front50.prod.netflix.net
  - name: mort
    group: credentials
    baseUrl: http://mort.prod.netflix.net
  - name: mayo
    group: config
    baseUrl: http://mayo.prod.netflix.net