{
  "exec": {
    "command": [
      {% for token in command %}
              "{{ token }}"{% if not loop.last %}, {% endif %}
      {% endfor %}
    ]
  },
  "initialDelaySeconds": {{ initialDelaySeconds }}
}
