{
  "containers": [
    {% for container in containers %}
    {{ container }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ],

  {% if imagePullSecrets != null %}
  "imagePullSecrets": [
    {% for secret in imagePullSecrets %}
    "name": "{{ secret }}" {% if not loop.last %} , {% endif %}
    {% endfor %}
  ],
  {% endif %}

  {% if initContainers %}
  "initContainers": [
    {% for c in initContainers %}
    {{ c }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ],
  {% endif %}

  {% if hostAliases %}
  "hostAliases": [
    {% for h in hostAliases %}
    {{ h }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ],
  {% endif %}

  {% if serviceAccountName != null %}
  "serviceAccountName": {{ serviceAccountName }},
  {% endif %}

  "terminationGracePeriodSeconds": {{ terminationGracePeriodSeconds }},

  "volumes": [
    {% for volume in volumes %}
    {{ volume }} {% if not loop.last %} , {% endif %}
    {% endfor %}
  ]
}