clouddriver:
  container_name: clouddriver
  env_file: ./compose.env
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - "SERVICES_FRONT50_BASEURL=http://$DOCKER_IP:8080"
  image: quay.io/spinnaker/clouddriver:master
  links:
    - redis
  ports:
    - "7002:7002"
deck:
  container_name: deck
  environment:
    - "API_HOST=http://$DOCKER_IP:8084"
    - DECK_HOST=0.0.0.0
    - DECK_PORT=9000
    - PROTOCOL=http
    - AUTH_ENABLED=false
    - "AUTH_ENDPOINT=http://$DOCKER_IP:8084/auth/user"
  image: quay.io/spinnaker/deck:master
  ports:
    - "9000:9000"
echo:
  container_name: echo
  env_file: ./compose.env
  environment:
    - "FRONT50_BASEURL=http://$DOCKER_IP:8080"
    - "ORCA_BASEURL=http://$DOCKER_IP:8083"
    - "JAVA_OPTS=-javaagent:/opt/echo/lib/jamm-0.2.5.jar"
  image: quay.io/spinnaker/echo:master
  ports:
    - "8089:8089"
front50:
  container_name: front50
  env_file: ./compose.env
  environment:
    - "JAVA_OPTS=-javaagent:/opt/front50/lib/jamm-0.2.5.jar"
  image: quay.io/spinnaker/front50:master
  ports:
    - "8080:8080"
gate:
  container_name: gate
  env_file: ./compose.env
  environment:
    - SERVICES_CLOUDDRIVER_HOST=clouddriver
    - SERVICES_ECHO_HOST=echo
    - SERVICES_FRONT50_HOST=front50
    - SERVICES_IGOR_HOST=igor
    - SERVICES_ORCA_HOST=orca
    - SERVICES_ROSCO_HOST=rosco
  image: quay.io/spinnaker/gate:master
  links:
    - redis
    - clouddriver
    - echo
    - front50
    - igor
    - orca
    - rosco
  ports:
    - "8084:8084"
igor:
  container_name: igor
  env_file: ./compose.env
  environment:
    - SERVICES_ECHO_HOST=echo
    - SERVICES_CLOUDDRIVER_HOST=clouddriver
  image: quay.io/spinnaker/igor:master
  links:
    - redis
    - clouddriver
    - echo
  ports:
    - "8088:8088"
orca:
  container_name: orca
  env_file: ./compose.env
  environment:
    - SERVICES_CLOUDDRIVER_HOST=clouddriver
    - SERVICES_ECHO_HOST=echo
    - SERVICES_FRONT50_HOST=front50
    - SERVICES_IGOR_HOST=igor
    - SERVICES_ROSCO_HOST=rosco
  image: quay.io/spinnaker/orca:master
  links:
    - redis
    - clouddriver
    - echo
    - front50
    - igor
    - rosco
  ports:
    - "8083:8083"
redis:
  command: "redis-server --appendonly yes"
  container_name: redis
  expose:
    - "6379"
  image: redis
rosco:
  container_name: rosco
  env_file: ./compose.env
  image: quay.io/spinnaker/rosco:master
  links:
    - redis
  ports:
    - "8087:8087"
fiat:
  container_name: fiat
  env_file: ./compose.env
  environment:
    - SERVICES_CLOUDDRIVER_HOST=clouddriver
    - SERVICES_FRONT50_HOST=front50
  image: quay.io/spinnaker/fiat:master
  links:
    - redis
    - clouddriver
    - front50
  ports:
    - "7003:7003"
