clouddriver: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
    - "/root/spinnakerconfig/aws:/root/.aws"
    - "/root/spinnakerconfig/gcp:/root/.gcp"
echo: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
#deck:
#  volumes: 
#    - "/root/spinnakerconfig/settings.js:/deck/settings.js"
front50: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
gate: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
igor: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
orca: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
rosco: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"
rush: 
  volumes: 
    - "/root/spinnakerconfig:/opt/spinnaker/config"