name: Build Cop

on:
  schedule:
  - cron: 0 11 1,15 * * # Extend rotation on the 1st and 15th of the month at 11:00 UTC
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-cop-rotation.yml'

jobs:
  extend:
    # Only run this on repositories in the 'spinnaker' org, not on forks.
    if: startsWith(github.repository, 'spinnaker/')
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2

    - id: dates
      run: |
        echo "::set-output name=day60::$(date '+%Y-%m-%d' -d '+60 days')"

    - name: extend schedule
      uses: spinnaker/rotation-scheduler@master
      with:
        args: |
          schedule extend --stop ${{ steps.dates.outputs.day60 }} --prune --github spinnaker,build-cops,${{ secrets.SPINNAKERRELEASE_GHA_BUILD_COP_TOKEN }} --schedule .github/build-cop/schedule.yaml --domains google.com,netflix.com,armory.io .github/build-cop/schedule.yaml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.SPINNAKERRELEASE_GHA_BUILD_COP_TOKEN }}
        title: "Extend build cop schedule to ${{ steps.dates.outputs.day60 }}"
        team-reviewers: build-cops
        body: |
          cc @spinnaker/build-cops
        labels: build-cop-rotation
        commit-message: |
          chore(build-cop): Update build cop rotation schedule
