name: Bump Dependencies

on:
  repository_dispatch:
    types: [bump-dependencies]

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: spinnaker/bumpdeps@master
      with:
        ref: ${{ github.event.client_payload.ref }}
        key: spinnakerGradleVersion
        repositories: echo,fiat,keiko
      env:
        GITHUB_OAUTH: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}
