name: Branch Build

on:
  pull_request:
  push:
    branches:
      - master
      - release-*

env:
  NODE_VERSION: 12.16.0

jobs:
  ci:
    # Meta-job that depends on the other job statuses.  Branch protection then checks this job status.
    name: Deck CI
    if: startsWith(github.repository, 'spinnaker/')
    needs: [test, build, functional-tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo test, build successful

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure package bumps are pure
        id: purebump
        run: scripts/assert_package_bumps_standalone.sh

      - uses: actions/setup-node@v1
        if: steps.purebump.outputs.ispurebump != 'true'
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        if: steps.purebump.outputs.ispurebump != 'true'
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        if: steps.purebump.outputs.ispurebump != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn --frozen-lockfile

      - name: Build Modules
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn modules

      - name: Unit Tests
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn test --single-run

  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure package bumps are pure
        id: purebump
        run: scripts/assert_package_bumps_standalone.sh

      - uses: actions/setup-node@v1
        if: steps.purebump.outputs.ispurebump != 'true'
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        if: steps.purebump.outputs.ispurebump != 'true'
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        if: steps.purebump.outputs.ispurebump != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn --frozen-lockfile

      - name: Build Modules
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn modules

      - name: Functional Tests
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn functional

  build:
    name: Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure package bumps are pure
        id: purebump
        run: scripts/assert_package_bumps_standalone.sh

      - uses: actions/setup-node@v1
        if: steps.purebump.outputs.ispurebump != 'true'
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        if: steps.purebump.outputs.ispurebump != 'true'
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        if: steps.purebump.outputs.ispurebump != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn --frozen-lockfile

      - name: Build Modules
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn modules

      - name: Yarn Build
        if: steps.purebump.outputs.ispurebump != 'true'
        run: yarn build
