name: Deck Kayenta
run-name: Deck Kayenta ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_call:
    inputs:
      publish-npm:
        description: Publish npm
        type: boolean
        default: true
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string
  workflow_dispatch:
    inputs:
      publish-npm:
        description: Publish npm
        type: boolean
        default: true
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  push:
    branches:
      - release-*
    paths:
      - 'deck-kayenta/**'
      - '.github/workflows/deck-kayenta.yml'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'deck-kayenta/**'
      - '.github/workflows/deck-kayenta.yml'

<<<<<<< HEAD
=======
# https://docs.npmjs.com/trusted-publishers#github-actions-configuration
permissions:
  id-token: write
  contents: write

>>>>>>> 4a1dafc454 (fix(deck): Attempt two of fixing deck publishing (#7406))
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generic-build-publish
        with:
          project: deck-kayenta
          publish: ${{ github.event_name != 'pull_request' }}
          publish-containers: false
          publish-debs: false
          publish-halconfig: false
          publish-npm: ${{ github.event_name == 'push' || inputs.publish-npm == true }}
          version-override: ${{ inputs.version-override }}
          integration-test: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
          gar-npm-password: ${{ secrets.GAR_NPM_PASSWORD }}
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
