name: Generate and Publish Docs

on:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  generate-docs:
    # Only run the root repository
    if: startsWith(github.repository, 'spinnaker/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout service repo
        uses: actions/checkout@v2
        with:
          path: service

      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: spinnaker/spinnaker.io
          path: docs

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Generate docs
        run: ./gradlew dokkaHtml --stacktrace
        working-directory: ./service

      - name: Copy docs
        run: |
          SOURCE_DIR=service/orca-api/build/dokka/html/
          TARGET_DIR=content/en/docs/reference/api/service-plugin-apis/orca-api/master/

          mkdir -p $TARGET_DIR
          cp -R $SOURCE_DIR $TARGET_DIR

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: ./docs
          title: 'docs(javadocs): Updating autogenerated javadocs'
          body: |
            Automated changes by `${{ github.workflow }}` in `${{ github.repository }}` ([Run ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})).
          token: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}

      - name: Output PR Info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
