name: ID Token Caller

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug OIDC Claims (Caller)
        uses: ./.github/actions/oidc-debugger-action
        with:
          audience: 'npm:registry.npmjs.org'
      - name: Call a child and check that too
        uses: ./.github/workflows/id-token-callee
        secrets: inherit
