name: Kubernetes Integration Tests

on: workflow_call

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx12g -Xms12g

jobs:
  it-test-kubernetes:
    strategy:
      matrix:
        kubectl-version:
          - 1.22.17
        kubernetes-image:
          - "kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570"
          - "kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31"
          - "kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72"
          - "kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb"
          - "kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8"
          - "kindest/node:v1.24.15@sha256:7db4f8bea3e14b82d12e044e25e34bd53754b7f2b0e9d56df21774e6f66a70ab"
          - "kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb"
          - "kindest/node:v1.22.17@sha256:f5b2e5698c6c9d6d0adc419c0deae21a425c07d81bbf3b6a6834042f25d4fba2"
          - "kindest/node:v1.21.14@sha256:8a4e9bb3f415d2bb81629ce33ef9c76ba514c14d707f9797a01e3216376ba093"
        include:
          - kubectl-version: 1.29.1
            kubernetes-image: "kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570"
          - kubectl-version: 1.28.6
            kubernetes-image: "kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31"
          - kubectl-version: 1.27.10
            kubernetes-image: "kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72"
          - kubectl-version: 1.26.13
            kubernetes-image: "kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb"
          - kubectl-version: 1.25.16
            kubernetes-image: "kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8"
          - kubectl-version: 1.24.17
            kubernetes-image: "kindest/node:v1.24.15@sha256:7db4f8bea3e14b82d12e044e25e34bd53754b7f2b0e9d56df21774e6f66a70ab"
          - kubectl-version: 1.23.17
            kubernetes-image: "kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb"
          - kubectl-version: 1.21.14
            kubernetes-image: "kindest/node:v1.21.14@sha256:8a4e9bb3f415d2bb81629ce33ef9c76ba514c14d707f9797a01e3216376ba093"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: |
            17
            11
          distribution: 'zulu'
      - name: Cache on push
        if: github.event_name == 'push'
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-cd-it-${{ github.sha }}
          # Restore build outputs from the previous commit (if successful), if current commit hasn't run successfully yet
          restore-keys: |
            ${{ runner.os }}-cd-it-${{ github.event.before }}
      - name: Cache on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-cd-it-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            ${{ runner.os }}-cd-it-${{ github.event.before }}
      - name: Kubernetes Provider Integration Tests
        run: |
          version=$(echo '${{ matrix.kubernetes-image }}' | grep -o 'v[0-9]*\.[0-9]*')
          ./gradlew --build-cache :clouddriver-kubernetes:integrationTest -Pkubernetes-image=${{ matrix.kubernetes-image }} -Pkubectl-version=${{ matrix.kubectl-version }} -Pkubernetes-version=${version}
