name: Kork
run-name: Kork ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'kork/**'
      - '.github/workflows/kork.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/generic-build-publish
        with:
          project: kork
          publish: false
          integration-test: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
