name: PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    # - uses: actions/cache@v1
    #   with:
    #     path: ~/.gradle
    #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    #     restore-keys: |
    #       ${{ runner.os }}-gradle-
    - uses: eskatos/gradle-command-action@v1
      env:
        GRADLE_OPTS: -Xmx6g -Xms6g -Dorg.gradle.daemon=false
      with:
        wrapper-directory: ./
        arguments: build javadoc 

