name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'
      - name: Prepare build variables
        id: build_variables
        run: |
          echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/}
          echo ::set-output name=VERSION::"$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')"
      - name: Build
        run: ./gradlew build ${{ steps.build_variables.outputs.REPO }}-web:installDist
      - name: Build slim container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.slim
          tags: |
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:latest"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:latest-slim"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}-slim"
      - name: Build ubuntu container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          tags: |
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:latest-ubuntu"
            "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}-ubuntu"
