name: Publish azure

on:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/azure/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      - name: publish azure
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          scripts/github_actions_publish.sh azure
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
