name: Update Monorepo
run-name: Update Monorepo (${{ inputs.remote-ref }})

on:
  workflow_dispatch:
    inputs:
      remote-ref:
        description: Remote ref to merge from (master, release-1.35.x, etc)
        default: master
      merge-with-ours:
        description: Merge with the --ours strategy
        type: boolean
        default: true

jobs:
  update-monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.remote-ref == 'master' && 'main' || inputs.remote-ref }}
          fetch-depth: 0

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}


      - uses: ./.github/actions/update-monorepo
        with:
          remote-ref: ${{ inputs.remote-ref }}
          github-pat: ${{ steps.app-token.outputs.token }}
          
